apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    command: ["/bin/sh", "-c", "while true; do echo $(date) >> /mnt/hostpath-volume/file.log; sleep 5; done"]
    volumeMounts:
    - mountPath: /one
      name: hostpath-volume
  volumes:
  - name: hostpath-volume
    hostPath:
      path: /home/vagrant
      type: DirectoryOrCreate

