apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-ebs-vol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-084dec17a79273083         
    fsType: ext4

